version: '3.8'

services:
  app:
    build: .
    container_name: app-financy-php
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  web:
    image: nginx:1.27-alpine
    container_name: app-financy-nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: app-financy-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_financy
      MYSQL_USER: app_financy
      MYSQL_PASSWORD: app_financy
    ports:
      - "3310:3306"
    volumes:
      - dbdata:/var/lib/mysql

  node:
    image: node:18-alpine
    container_name: app-financy-node
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: ["sh", "-c", "npm install && npm run dev"]
    depends_on:
      - app

volumes:
  dbdata:
